### ISSUE TITLE
Save Button?

### ISSUE THREAD

**Issue by BennetBartmann** [BennetBartmann/Jinawa#22]
Hi,

I miss something like a "Save" Button at the Page, it must not be a save button as such, but a possibility to go back to the Staple without using the back button. Preferably I would wish for a discette... but I don't know if ppl. would be disturbed by it.

Kind regards
Ben

**Comment by Trve92** [comment]
Save Button in the Writer View? Do you prefer a Bar on the Top including a Save/Back Button an Char-count etc.? Twice the height as the current one is now?
